/**
 * Action types for currency pair tracking 
 */

export const OPEN_CURRENCY_PAIR_TRACKING_CONNECTION = 'OPEN_CURRENCY_PAIR_TRACKING_CONNECTION';
export const OPEN_CURRENCY_PAIR_TRACKING_CONNECTION_SUCCESS = 'OPEN_CURRENCY_PAIR_TRACKING_CONNECTION_SUCCESS';
export const OPEN_CURRENCY_PAIR_TRACKING_CONNECTION_ERROR = 'OPEN_CURRENCY_PAIR_TRACKING_CONNECTION_ERROR';
export const CLOSE_CURRENCY_PAIR_TRACKING_CONNECTION = 'CLOSE_CURRENCY_PAIR_TRACKING_CONNECTION';
export const CLOSE_CURRENCY_PAIR_TRACKING_CONNECTION_SUCCESS = 'CLOSE_CURRENCY_PAIR_TRACKING_CONNECTION_SUCCESS';
export const CLOSE_CURRENCY_PAIR_TRACKING_CONNECTION_ERROR = 'CLOSE_CURRENCY_PAIR_TRACKING_CONNECTION_ERROR';
export const RECEIVED_CURRENCY_PAIR_TRACKING_MESSAGE = 'RECEIVED_CURRENCY_PAIR_TRACKING_MESSAGE';