export const GET_CURRENT_AVERAGE = 'GET_CURRENT_AVERAGE';
export const GET_CURRENT_AVERAGE_SUCCESS = 'GET_CURRENT_AVERAGE_SUCCESS';
export const GET_CURRENT_AVERAGE_SET_SUCCESS = 'GET_CURRENT_AVERAGE_SET_SUCCESS';
export const GET_CURRENT_AVERAGE_ERROR = 'GET_CURRENT_AVERAGE_ERROR';