version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - /app
    ports:
      - "3001:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"